name: chess
description: "A new Flutter project."

publish_to: 'none'  


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  squares: ^1.2.1
  bishop: ^1.4.4
  square_bishop: ^0.3.0
  provider: ^6.0.0 
  stockfish: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets: 
  - assets/pieces/
  - assets/images/


