name: chess_game
description: "A new Flutter project."

publish_to: 'none'  


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  squares: ^1.2.1
  bishop: ^1.4.4
  square_bishop: ^0.3.0
  provider: ^6.0.0 
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  crypto: ^3.0.0
  firebase_database: ^11.2.0
  uuid: ^4.4.0
  equatable: ^2.0.5
  simple_chess_board: ^1.3.0
  chess: ^0.8.1
  chess_lib: ^0.1.0+2
  font_awesome_flutter: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets: 
  - assets/pieces/
  - assets/images/


